on:
  push:
    branches:
      - main
jobs:
  release:
    name: Semantic Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release Server
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: main
          working_directory: ./how-ai-backend
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy README
        run: cp README.md how-ai/README.md

      - name: Release Client
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: main
          working_directory: ./how-ai
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
